ALTER TABLE marega.leases

ADD COLUMN IF NOT EXISTS pdf_path TEXT,

ADD COLUMN IF NOT EXISTS signed BOOLEAN NOT NULL DEFAULT FALSE,

ADD COLUMN IF NOT EXISTS signed_at TIMESTAMP,

ADD COLUMN IF NOT EXISTS terminated_at TIMESTAMP,

ADD COLUMN IF NOT EXISTS termination_reason TEXT;